name: linko
description: Community assistance app connecting people who need help with nearby volunteers
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Navigation
  go_router: ^13.0.0

  # Utilities
  http: ^1.2.2
  intl: ^0.20.2
  socket_io_client: ^3.0.2
  uuid: ^4.3.3
  flutter_map: ^7.0.2

  geolocator: ^13.0.2
  latlong2: ^0.9.1

  # Storage
  shared_preferences: ^2.2.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
